### ISSUE TITLE
will it work for any classifier ?

### ISSUE THREAD

**Issue by Sandy4321** [Ekeany/Boruta-Shap#1]
great code
but will it work for any classifier for example binary classification by xgboost or lightgbm or catboost?

**Comment by Ekeany** [comment]
Hi Sandy,

This project is still a working progress but yes both SHAP and Permutation importance will work on any model.

**Comment by Sandy4321** [comment]
So if I have permutation importance why I still need SHAP?
Some people say that SHAP needed when permutation importance can not be done due to computational complexity?

**Comment by Ekeany** [comment]
Hi Sandy,

You are correct permutation importance is very computationally, as it scales linearly with both the number of observations and columns in the datasets. Certainly some SHAP variants are faster but they are model dependent so this is not always the case.  

There is also a difference between both importance measures: Permutation feature importance is based on the mean decrease in model performance. Whereas, SHAP is the average marginal contribution from that feature. SHAP results have also proven to be more aligned with human intuition, and from experience I find it to give more accurate results relative to permutation importance.
