### ISSUE TITLE
[INF] Please push the latest version of the code to PyPI

### ISSUE THREAD

**Issue by dandavies99** [Ekeany/Boruta-Shap#119]
Description
===========
The code in the repository has been updated in PR #114 to fix Issues #111 and #118. However, users are still struggling (see comments on those issues) to use the code because the version installed using the `pip install` instructions on the README still install [an old version from PyPI](https://pypi.org/project/BorutaShap/#history).

Reasoning
=========
Updating the version on PyPI will fix the import errors associated with the Boston dataset.

Implementation
==============
Push new version to PyPI.

Tasks
=====
Push new version to PyPI.

**Comment by Ekeany** [comment]
Code has been updated on pypi https://pypi.org/project/BorutaShap/
