### ISSUE TITLE
[INF] Merge to BorutaPy (sklearn-contrib)

### ISSUE THREAD

**Issue by ThomasBury** [Ekeany/Boruta-Shap#12]
Description
===========
Merge those to BorutaPy
I did a similar PR, with almost all the same modifications. 

Reasoning
=========
It makes sense to merge to the parent BorutaPy package to avoid duplicates
Existing PR can be then replaced or merge with the present package (FYI https://github.com/scikit-learn-contrib/boruta_py/pull/77).

It'll be part of sklearn-contrib, which is actually a nice way to have visibility and a significant impact on the ML community.

Implementation
==============
Overview of possible implementations

Tasks
=====
- Reach out the BorutaPy the maintainers, discuss the merging
- [ ] Task 2
- [ ] Task 3

**Comment by Ekeany** [comment]
Hi Thomas,

I have no issues with the proposed merge makes sense to unify all the methods into a single package.

**Comment by ThomasBury** [comment]
Hi Ekeany,

I opened an issue, [see here](https://github.com/scikit-learn-contrib/boruta_py/issues/80), to discuss the changes/merge. Feel free to be part of the discussion (or not).

There are great things in your package, I think I proposed +- the same in my PR but not necessarily as well written than your code. You can still have a look to [the PR](https://github.com/scikit-learn-contrib/boruta_py/pull/77). Maybe there are some parts that you can re-use if the merge with Boruta-Py is not granted. In that case, I'll re-read carefully your code and if I have any proposition, I'll make a PR.

**Comment by ThomasBury** [comment]
Hi Ekeany,

I'll close it since the Boruta owner doesn't seem in favour of a merge. Maybe, he'll reconsider at some point.
