### ISSUE TITLE
[BUG] TypeError: __init__() got an unexpected keyword argument 'feature_perturbation'

### ISSUE THREAD

**Issue by mvpalheta** [Ekeany/Boruta-Shap#15]
TypeErrorTraceback (most recent call last)
<ipython-input-65-3c7bc9167d3d> in <module>
      8                               classification=True)
      9 
---> 10 Feature_Selector.fit(X=X_train_rs, y=y_train_rs, n_trials=100, random_state=0)

~/.local/lib/python3.6/site-packages/BorutaShap.py in fit(self, X, y, n_trials, random_state, sample)
    281 
    282 
--> 283                 self.X_feature_import, self.Shadow_feature_import = self.feature_importance()
    284                 self.update_importance_history()
    285                 self.hits += self.calculate_hits()

~/.local/lib/python3.6/site-packages/BorutaShap.py in feature_importance(self)
    511         if self.importance_measure == 'shap':
    512 
--> 513             self.explain()
    514             vals = self.shap_values
    515             vals = self.calculate_Zscore(vals)

~/.local/lib/python3.6/site-packages/BorutaShap.py in explain(self)
    595 
    596 
--> 597         explainer = shap.TreeExplainer(self.model, feature_perturbation = "tree_path_dependent")
    598 
    599 

TypeError: __init__() got an unexpected keyword argument 'feature_perturbation'

**I use shap 0.32.1**

**Comment by Ekeany** [comment]
Hi,

I believe you need to update your version of SHAP to 0.34.0 I will add a lower limit on the SHAP dependency in the setup.py now.

**Comment by mvpalheta** [comment]
Many thanks. I updated and  its works for me
