### ISSUE TITLE
How to cite this library in an academic text

### ISSUE THREAD

**Issue by Devilmoon** [Ekeany/Boruta-Shap#17]
Hello,

I would need to cite this library in my thesis, but don't know if you have a preferred citation style. Also, does this repo have a DOI? (https://github.blog/2014-05-14-improving-github-for-science/).

I am currently using this style:
```
@misc{BorutaShap,
  author = {Eoghan, Keany},
  title = {Boruta-Shap},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/Ekeany/Boruta-Shap}},
  DOI = {},
  commit = {ffc1ca2b71235ebe353e89185021635abfffc712}
}
```

Please do let me know if you'd like a different style or if you can provide a DOI!

**Comment by Ekeany** [comment]
Bit late now but I created a DOI object for the project it can be found at the top of the READme file.
