### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by nils-fl** [Ekeany/Boruta-Shap#19]
Hi,

thank you very much for this great enhancement of the Boruta selection in Python!
I am working with thusands of features and would like to have some kind ob verbose option. I just comment out the prints, but that should not really be the way to go.

Description
===========
Option to prevent printing all selected and not-selected features.

Reasoning
=========
With thousands of features the output gets pretty messy.

Implementation
==============
An argument to disable:
```
        print(str(len(self.accepted))  + ' attributes confirmed important: ' + str(self.accepted))
        print(str(len(self.rejected))  + ' attributes confirmed unimportant: ' + str(self.rejected))
        print(str(len(self.tentative)) + ' tentative attributes remains: ' + str(self.tentative))
```

**Comment by Ekeany** [comment]
Thanks for the issue,
This has been added to the latest version of BorutaShap
