### ISSUE TITLE
will it work for multidimensional matrix? like the type of tif?

### ISSUE THREAD

**Issue by Yannikuni** [Ekeany/Boruta-Shap#2]
It was an excellent improved Boruta algorithm, but I wanna do feature selection of the multiband images. The data type is tif and each band represents for a kind of feature. I wonder whether the algorithm is able to work for multidimensional matrix([200, 200, 11]) as input features or not?

**Comment by Ekeany** [comment]
Hi Yannikuni,

This package at the moment only works for tree based learners so in it's current 3D format it couldn't be used. I don't have much experience with tif data however if you can convert your data into a 2D array similar to this [article](https://towardsdatascience.com/neural-network-for-satellite-data-classification-using-tensorflow-in-python-a13bcf38f3e1)  and store it in a pandas Dataframe then you could use this package.
