### ISSUE TITLE
[BUG] missing values check on training data shouldn't be done for Catboost and XGBoost

### ISSUE THREAD

**Issue by jmilhomens** [Ekeany/Boruta-Shap#21]
Describe the bug
================
Catboost and XGBoost accept missing values in the training set. The training set shouldn't be checked for missing values when using these algorithms.

To Reproduce
============
run:
```
from BorutaShap import BorutaShap, load_data
from catboost import CatBoostClassifier
import numpy as np

X, y = load_data(data_type="classification")
# introduce one missing value
X.iloc[4, 5] = np.nan

model = CatBoostClassifier()
Feature_Selector = BorutaShap(model, importance_measure="shap", classification=True)
Feature_Selector.fit(X=X, y=y, n_trials=100, random_state=0)
```
Output: `ValueError: There are missing values in your Data`

Expected behavior
=================
The fit shouldn't throw an error. The model can cope with missing values.

**Comment by Ekeany** [comment]
Thanks for the issue,
This has been changed in the latest version, which does not raise an error for any of the models that can handle NA's on there own.
