### ISSUE TITLE
What is Average Feature Importance in Feature_Selector.results_to_csv()?

### ISSUE THREAD

**Issue by tmontana** [Ekeany/Boruta-Shap#24]
Hi.  Wondering how one should interpret average feature importance.  Are these shap values?  In that case very negative values should be retained (as one should use absolute values).  If not then what do they represent?

Many thanks,

**Comment by Ekeany** [comment]
Hi,

Both the absolute SHAP and GAIN values are normalized using the Z-score formula. This process can produce negative values which you have noticed, these values are simply just below the mean value I believe. The average feature importance score is then simply the average Z-Score value for each feature .

Hope this helps.

**Comment by tmontana** [comment]
Hi makes sense but is there a way to get the original data before z-scoring just for sanity check?  My values range from 23 to -0.29 which is a strange highly skewed distribution of z-scores.  I would have expected something in the range of -3 to +3.

Many thanks,

**Comment by Ekeany** [comment]
Hi,

Just added this feature in the latest release. In the fit method you can choose to normalize the importance metric or not.

**Comment by tmontana** [comment]
That's great.  I'll test this out this week and revert.  Many thanks
