### ISSUE TITLE
How use Borutashap with imblearn Pipeline for correct CV eval? 

### ISSUE THREAD

**Issue by Gilianp** [Ekeany/Boruta-Shap#30]
In context of imbalanced data, how use Borutashap with imblearn Pipeline library for correct evaluation? Imblearn Pipeline just apply balance method (over-sampling/under-sampling) in train "part" of cross validation, how can Borutashap in this case?

**Comment by Ekeany** [comment]
Hi,

There is currently no functionality to perform "under sampling" or "over sampling". The only way to directly combat imbalanced datasets, is to use the inbuilt functionality of the models themselves ie  "class_weight = 'balanced'" in the sklearn "Random Forest" or "XGBoost's" scale_pos_weight factor, both of which can help with class imbalances.

**Comment by Gilianp** [comment]
Ok, thanks Ekeany!
