### ISSUE TITLE
[ENH] Reference for isolation forest sampling

### ISSUE THREAD

**Issue by lgmoneda** [Ekeany/Boruta-Shap#33]
Current Situation
=================
First of all, thanks for sharing this library!

By reading the library doc and code, I've got interested in the sampling strategy to reduce the time:

> It finds this sample by comparing the distributions produced by an isolation forest of the sample and the data using ks-test. From experiments, this procedure can reduce the run time up to 80% while still creating a valid approximation of the entire data set. 

Is there any reference about how this sampling strategy is better than random sampling to estimate shap average importance of the features?

I'm thinking about extracting this piece of logic to use it directly in the task of doing shap values with a sample and reduce its run time. 

Enhancement
===========
Add references, if they exist, for the isolation forest sampling.

Reasoning
=========
Make docs more complete.

Implementation
==============
Add a link to the readme.

**Comment by Ekeany** [comment]
Hi lgmoneda,

It was just an idea I had to reduce the run time for shapley values to be computed. So I am not aware of any references or previous works that describe this as a sampling strategy.

**Comment by lgmoneda** [comment]
@Ekeany thanks!
