### ISSUE TITLE
Sample Weight Support for Regression Problems [ENH]

### ISSUE THREAD

**Issue by kmedved** [Ekeany/Boruta-Shap#37]
Current Situation
=================
Most scikit-learn estimators allow for passing sample weights along with the X and y values as an optional parameter. These weights are often key for regression problems. Currently it seems like Boruta-Shap does not support this (unless I'm missing something).

Enhancement
===========
Add support for sample_weights.

Implementation
==============
Given most scikit-learn compatible regression estimators already allow this, including RF and Xgboost, I think this should be possible to add just by passing a sample_weight parameter to the .fit() call of the relevant estimator. I may be missing some complexity here however. I appreciate the help.

**Comment by Ekeany** [comment]
Hi,

I think this is a good idea, feel free to make a pull request if you want. I think it may be possible to add a **kwargs list to the sklearn fit() function.

**Comment by LuiNov** [comment]
Hey @kmedved, 

I saw your file. But how do I execute the Boruta function together with my survey weights now ? 

Could you like give a short "tutorial" how to run the code? 

Thanks, 
Luise

**Comment by Ekeany** [comment]
Looks great,

Do you want to make a pull request ?
To add it to the main package ?

**Comment by LuiNov** [comment]
Ok....... I'm so sorry..... I wondered where to find the package.... Then I saw it's python not R..... 
Do you know about a way to implement this in R-Language? I know that I could switch to Python but I am not familiar with the language....

**Comment by Ekeany** [comment]
Yeh the package is in python, I honestly don't think there is an equivalent
package in R.

Sorry

**Comment by LuiNov** [comment]
:-( Ok 
But thanks again for your help!! I am using it without weights atm. I am comparing three countries from the WVS-Dataset. My weights are correcting for population size, gender, age and regions. For the moment I implemented it without weights. 
I thought about "cheating" by multiplying my outcome variable with the weights and run on the "Outcome Tilda". Could I do this or is this completely wrong? For sure I won't fit my regression in that way.

**Comment by kmedved** [comment]
> Looks great, Do you want to make a pull request ? To add it to the main package ?

Do you mean something other than: https://github.com/Ekeany/Boruta-Shap/pull/60? Just want to make sure I understand.

**Comment by Ekeany** [comment]
Oh sorry didn't see that pull request will merge it now thanks again for
the help

**Comment by kmedved** [comment]
Thanks @Ekeany
