### ISSUE TITLE
BorutaShap throws error if there are missing values in the data even if the model used is lightgbm [BUG]

### ISSUE THREAD

**Issue by Nitinsiwach** [Ekeany/Boruta-Shap#44]
Describe the bug
================
Currently, BorutaShap throws error if there are missing values in the data even if the model used is lightgbm. The reason is that the code checks for string 'lgbm' instead of 'lightgbm' as a marker to see if the model used is 'lightgbm'

LIne 179 in BorutaShap.py 
`models_to_check = ('xgb', 'catboost', 'lgbm')`
should be
`models_to_check = ('xgb', 'catboost', 'lgbm', 'lightgbm')`
Since,
`model=LGBMClassifier()`
`print(type(model))`
`#lightgbm.sklearn.LGBMClassifier`

**Comment by Ekeany** [comment]
Hi,

Thanks for spotting this bug have updated the code as per your solution.

**Comment by Ekeany** [comment]
merged your pull request thanks again
