### ISSUE TITLE
[BUG] `check_missing_values` warning not done correctly

### ISSUE THREAD

**Issue by timlod** [Ekeany/Boruta-Shap#50]
Describe the bug
================
I'm using a LightGBM model, and was surprised to see BorutaShap complains about missing values in my data.

To Reproduce
============
1. Make classification dataset with missing values
2. Create LGBMClassifier
3. Run `fit()`

Expected behavior
=================
The warning as defined in `check_missing_values` should be triggered, as this is a LGBM model:
`print('Warning there are missing values in your data !')`
instead of the error message.

Fix
====
This: `if model_name.startswith(models_to_check):` - line 184 - won't work, as an initialised LGBM model (name currently computed with `model_name = str(type(self.model)).lower()`) is `<class 'lightgbm.sklearn.lgbmclassifier'>`.
That clearly doesn't start with `lgbm`.

Instead, one could do, for example: `if any([x in model_name for x in models_to_check]):` to fix this issue.

**Comment by Ekeany** [comment]
Hi,

Thanks for spotting this bug I will update accordingly as per your code.
