### ISSUE TITLE
Speeding up of the shap calculations[ENH]

### ISSUE THREAD

**Issue by rphilip-sonasoft** [Ekeany/Boruta-Shap#69]
Current Situation
=================
As it stands, BorutaShap works perfectly on smaller datasets with the importance_measure = "shap". You would have to resort to gini, if the dataset was even slightly on the larger side. 

Enhancement
===========
Simply adding an approximate = True flag in each of the lines where explainer.shap_values() is, speeds up the process exponentially. This could be added as an option. During my hacky experimentation, it reduced the time of processing of shap values by almost 50x. 
This solution was also used by the creators of the shap library to make it more usable

Reasoning
=========
The library will be usable on much larger datasets.

Implementation
==============
As mentioned before, add in the approximate = True flag in the shap_value calls.

Tasks
=====
- [ ] Add in approximate = True on [here](https://github.com/Ekeany/Boruta-Shap/blob/8c9782a7af1b595504bf29ee0bfe74571d6b7d17/src/BorutaShap.py#L720) and [here](https://github.com/Ekeany/Boruta-Shap/blob/8c9782a7af1b595504bf29ee0bfe74571d6b7d17/src/BorutaShap.py#L737) and [here](https://github.com/Ekeany/Boruta-Shap/blob/8c9782a7af1b595504bf29ee0bfe74571d6b7d17/src/BorutaShap.py#L744) and [here](https://github.com/Ekeany/Boruta-Shap/blob/8c9782a7af1b595504bf29ee0bfe74571d6b7d17/src/BorutaShap.py#L761)

**Comment by Ekeany** [comment]
Perfect thanks Phillip just implement your suggestion in the latest commit
