### ISSUE TITLE
[BUG] broken link in docs

### ISSUE THREAD

**Issue by venaturum** [Ekeany/Boruta-Shap#89]
Describe the bug
================

 The following link is used in Feature Selection docstring in README.md
https://compstat-lmu.github.io/iml_methods_limitations/pfi-data.html#introduction-to-test-vs.training-data

It is broken.

**Comment by MauritsDescamps** [comment]
I believe this is the correct link: [https://slds-lmu.github.io/iml_methods_limitations/pfi-data.html](url)
